### PR TITLE
Add Nesterov, AdaGrad, RMSProp and AdaDelta optimizers.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
That's all I had in DeepFried, but I just read the Adam paper and will add it soon.

Don't merge this PR yet, I'd still like to add an example which uses all of them, but probably not today anymore, it's getting late here.

("WIP" in title means Work In Progress)

### CODE REVIEW

**Comment by ikostrikov** [comment]
It looks decent but I agree that we need  examples.

**Comment by lucasb-eyer** [comment]
For the examples, I'm waiting for a few example-code-related PRs I have in the queue, so it'll be in a few days. (No stress :sunglasses:)

**Comment by ikostrikov** [comment]
Is work still in progress?

**Comment by lucasb-eyer** [comment]
Yeah, examples were waiting for #18 and a few that will follow, hopefully today. I'll let you know here once it's ready for review.

**Comment by lucasb-eyer** [comment]
Since the PRs this was waiting for have been merged, I added the examples and this is now ready for review.

One thing I'm not sure of: the example is essentially the same as the MNIST example, except that it runs each optimizer for five epochs. Do we want both, or should we merge this into the MNIST example?

**Comment by lucasb-eyer** [comment]
rebased.

**Pull request closed without merging**
