### PR TITLE
Model zoo with Pretrained VGG16/19

### PR DESCRIPTION
**Pull request by lucasb-eyer**
Adds a model "zoo" à la Caffe. Currently, this contains VGG16 and VGG19, it allows to just create the model (and then train yourself) or download the pretrained ILSVRC weights from the internet and create a pretrained version of the net. The latter is done in the example.

Again, I made the commits so that it's best to read the commits individually, the commit message contains a lot of information.

The two large `json` files will move from the example to the `data` submodule, whose PR will follow in a few days.

Looking forward to your feedback; especially, I think you may not like the change of parameters to `SpatialConvolutionCUDNN`?

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Also, this needed the `SpatialSoftMaxCUDNN` which you introduced in #13 but isn't merged yet, so i just put it in here and slightly adapted it.

**Comment by ikostrikov** [comment]
I think that we should remove json files from github.

**Comment by lucasb-eyer** [comment]
Yeah, I felt uncomfortable adding them, but for some reason didn't think of putting them into a github gist and using the `download` function included in this very PR. [That's what I've done now](https://gist.github.com/lucasb-eyer/237d03b9fcdb0fe03bce).

I've also undone the change to the `border` parameter of `SpatialConvolutionCUDNN` so that it's back to the same as Torch7 by default, and the string version is just an alternative, as per our discussion. Also undone the change to `Module.parameters()` for the same reason.

**Comment by ikostrikov** [comment]
Interface is still different from Torch7.

**Pull request closed without merging**
